services:
  - type: web
    name: frontend
    env: node
    buildCommand: bun install && bun run build
    startCommand: node .output/server/index.mjs
    rootDir: frontend
    envVars:
      NUXT_API_URL: https://soog.onrender.com # Example for connecting frontend to backend

  - type: web
    name: backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    rootDir: backend